import type { Metadata } from 'next'
import { DM_Sans, Playfair_Display } from 'next/font/google'
import { ThemeProvider } from '@/context/ThemeContext'
import { CookieConsent } from '@/components/CookieConsent'
import './globals.css'

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-dm-sans',
  display: 'swap',
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['600', '700', '800'],
  variable: '--font-playfair',
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL('https://lexai.com.br'),
  title: 'LexAI — Inteligencia Juridica · uma marca Vanix Corp',
  description: 'LexAI, uma marca Vanix Corp. Plataforma de inteligencia artificial para escritorios de advocacia. 22 agentes IA especializados: analise de documentos, pesquisa jurisprudencial, redacao de pecas, negociacao, calculos juridicos e mais.',
  keywords: 'lexai, vanix corp, assistente juridico, inteligencia artificial, direito, advogado, escritorio advocacia, jurisprudencia, pecas processuais, ia juridica',
  authors: [{ name: 'Vanix Corp' }],
  openGraph: {
    title: 'LexAI — Assistente Juridico Inteligente',
    description: '22 agentes de IA para profissionais do Direito. Analise documentos, pesquise jurisprudencia e gere pecas processuais.',
    type: 'website',
    locale: 'pt_BR',
    url: 'https://lexai.com.br',
    siteName: 'LexAI · Vanix Corp',
    // Images auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'LexAI',
    description: '22 agentes de IA para escritorios de advocacia. Analise documentos, pesquise jurisprudencia e gere pecas processuais.',
    // Images auto-generated by src/app/opengraph-image.tsx
  },
  alternates: {
    canonical: 'https://lexai.com.br',
  },
  robots: { index: true, follow: true },
}

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'O que e a LexAI?',
      acceptedAnswer: { '@type': 'Answer', text: 'LexAI e uma plataforma de inteligencia artificial com 22 agentes especializados no Direito brasileiro. Cada agente resolve uma tarefa especifica: analise de documentos, pesquisa de jurisprudencia, redacao de pecas, calculos processuais, compliance LGPD e mais.' },
    },
    {
      '@type': 'Question',
      name: 'Quanto custa a LexAI?',
      acceptedAnswer: { '@type': 'Answer', text: 'Os planos comecam em R$ 1.399 por mes por advogado (plano Escritorio, 1-5 advogados). O plano Firma custa R$ 1.459 (6-15 advogados) e o Enterprise R$ 1.599 (16+ advogados). Todos incluem 7 dias de teste gratuito.' },
    },
    {
      '@type': 'Question',
      name: 'A LexAI inventa jurisprudencia?',
      acceptedAnswer: { '@type': 'Answer', text: 'Nao. Cada citacao de jurisprudencia retorna com ementa, tribunal, data de julgamento e link. O sistema foi projetado para negar a resposta quando nao puder ser sustentada por fonte rastreavel.' },
    },
    {
      '@type': 'Question',
      name: 'Meus dados de cliente estao seguros?',
      acceptedAnswer: { '@type': 'Answer', text: 'Sim. A LexAI processa dados no Brasil quando possivel, usa criptografia em repouso e em transito, isola completamente os dados entre escritorios e nunca usa dados de clientes para treinar modelos. Conformidade total com a LGPD (Lei 13.709/2018).' },
    },
    {
      '@type': 'Question',
      name: 'Posso cancelar quando quiser?',
      acceptedAnswer: { '@type': 'Answer', text: 'Sim. Todos os planos podem ser cancelados a qualquer momento, sem multa, sem burocracia. O acesso permanece ativo ate o fim do periodo ja pago.' },
    },
  ],
}

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'LexAI',
  applicationCategory: 'BusinessApplication',
  applicationSubCategory: 'LegalTech',
  operatingSystem: 'Web',
  inLanguage: 'pt-BR',
  url: 'https://lexai.com.br',
  description: 'Plataforma de inteligencia artificial para advogados brasileiros. 22 agentes IA especializados em analise de documentos, pesquisa jurisprudencial, redacao de pecas, calculos juridicos e mais.',
  publisher: {
    '@type': 'Organization',
    name: 'Vanix Corp',
    url: 'https://vanix.com.br',
  },
  offers: {
    '@type': 'AggregateOffer',
    priceCurrency: 'BRL',
    lowPrice: '1399',
    highPrice: '1599',
    offerCount: 3,
    offers: [
      { '@type': 'Offer', name: 'Escritorio', price: '1399', priceCurrency: 'BRL', category: 'subscription', description: '1-5 advogados · 5 agentes essenciais' },
      { '@type': 'Offer', name: 'Firma', price: '1459', priceCurrency: 'BRL', category: 'subscription', description: '6-15 advogados · 22 agentes' },
      { '@type': 'Offer', name: 'Enterprise', price: '1599', priceCurrency: 'BRL', category: 'subscription', description: '16+ advogados · 22 agentes + agentes customizados' },
    ],
  },
  featureList: [
    'Analise de documentos juridicos',
    'Pesquisa de jurisprudencia',
    'Redacao de pecas processuais',
    'Calculo de prazos',
    'Resumo automatico',
    'Traducao juridica',
    'Simulado OAB',
    'Conformidade LGPD',
  ],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: `
          (function() {
            try {
              var t = localStorage.getItem('lexai-theme');
              if (!t) t = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
              document.documentElement.setAttribute('data-theme', t);
            } catch(e) {
              document.documentElement.setAttribute('data-theme', 'dark');
            }
          })();
        `}} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
      </head>
      <body className={`${dmSans.variable} ${playfair.variable}`}>
        <a href="#main-content" className="skip-link">Pular para o conteudo</a>
        <ThemeProvider>{children}</ThemeProvider>
        <CookieConsent />
      </body>
    </html>
  )
}
