import type { Metadata } from 'next'
import { DM_Sans, Playfair_Display } from 'next/font/google'
import { ThemeProvider } from '@/context/ThemeContext'
import { CookieConsent } from '@/components/CookieConsent'
import { MicrosoftClarity } from '@/components/MicrosoftClarity'
import { SITE_URL } from '@/lib/site-url'
import './globals.css'

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-dm-sans',
  display: 'swap',
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['600', '700', '800'],
  variable: '--font-playfair',
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: 'Pralvex — Inteligencia Juridica',
  description: 'Pralvex. Plataforma de inteligencia artificial para escritorios de advocacia. 27 agentes IA especializados: analise de documentos, pesquisa jurisprudencial, redacao de pecas, negociacao, calculos juridicos e mais.',
  keywords: 'pralvex, assistente juridico, inteligencia artificial, direito, advogado, escritorio advocacia, jurisprudencia, pecas processuais, ia juridica',
  authors: [{ name: 'Pralvex' }],
  openGraph: {
    title: 'Pralvex — Assistente Juridico Inteligente',
    description: '27 agentes de IA para profissionais do Direito. Analise documentos, pesquise jurisprudencia e gere pecas processuais.',
    type: 'website',
    locale: 'pt_BR',
    url: SITE_URL,
    siteName: 'Pralvex',
    // Images auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Pralvex',
    description: '27 agentes de IA para escritorios de advocacia. Analise documentos, pesquise jurisprudencia e gere pecas processuais.',
    // Images auto-generated by src/app/opengraph-image.tsx
  },
  alternates: {
    canonical: SITE_URL,
  },
  robots: { index: true, follow: true },
}

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'O que e a Pralvex?',
      acceptedAnswer: { '@type': 'Answer', text: 'Pralvex e uma plataforma de inteligencia artificial com 27 agentes especializados no Direito brasileiro. Cada agente resolve uma tarefa especifica: analise de documentos, pesquisa de jurisprudencia, redacao de pecas, calculos processuais, compliance LGPD e mais.' },
    },
    {
      '@type': 'Question',
      name: 'Quanto custa a Pralvex?',
      acceptedAnswer: { '@type': 'Answer', text: 'Os planos comecam em R$ 1.399 por mes por advogado (plano Escritorio, 1-5 advogados). O plano Firma custa R$ 1.459 (6-15 advogados) e o Enterprise R$ 1.599 (16+ advogados). Todos incluem demo de 50 minutos gratis pra testar antes de assinar.' },
    },
    {
      '@type': 'Question',
      name: 'A Pralvex inventa jurisprudencia?',
      acceptedAnswer: { '@type': 'Answer', text: 'Nao. Cada citacao de jurisprudencia retorna com ementa, tribunal, data de julgamento e link. O sistema foi projetado para negar a resposta quando nao puder ser sustentada por fonte rastreavel.' },
    },
    {
      '@type': 'Question',
      name: 'Meus dados de cliente estao seguros?',
      acceptedAnswer: { '@type': 'Answer', text: 'Sim. A Pralvex processa dados no Brasil quando possivel, usa criptografia em repouso e em transito, isola completamente os dados entre escritorios e nunca usa dados de clientes para treinar modelos. Conformidade total com a LGPD (Lei 13.709/2018).' },
    },
    {
      '@type': 'Question',
      name: 'Posso cancelar quando quiser?',
      acceptedAnswer: { '@type': 'Answer', text: 'Sim. Todos os planos podem ser cancelados a qualquer momento, sem multa, sem burocracia. O acesso permanece ativo ate o fim do periodo ja pago.' },
    },
  ],
}

const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${SITE_URL}/#organization`,
  name: 'Pralvex',
  legalName: 'Pralvex',
  url: SITE_URL,
  logo: `${SITE_URL}/apple-icon`,
  description: 'Pralvex e a plataforma de inteligencia artificial para escritorios de advocacia brasileiros.',
  foundingDate: '2025',
  sameAs: [
    SITE_URL,
  ],
  contactPoint: {
    '@type': 'ContactPoint',
    email: 'contato@pralvex.com.br',
    contactType: 'customer support',
    areaServed: 'BR',
    availableLanguage: ['Portuguese'],
  },
  areaServed: { '@type': 'Country', name: 'Brasil' },
}

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': `${SITE_URL}/#website`,
  name: 'Pralvex',
  alternateName: 'Pralvex',
  url: SITE_URL,
  inLanguage: 'pt-BR',
  publisher: { '@id': `${SITE_URL}/#organization` },
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${SITE_URL}/empresas?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
}

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  '@id': `${SITE_URL}/#software`,
  name: 'Pralvex',
  applicationCategory: 'BusinessApplication',
  applicationSubCategory: 'LegalTech',
  operatingSystem: 'Web',
  inLanguage: 'pt-BR',
  url: SITE_URL,
  description: 'Plataforma de inteligencia artificial para advogados brasileiros. 27 agentes IA especializados em analise de documentos, pesquisa jurisprudencial, redacao de pecas, calculos juridicos e mais.',
  publisher: { '@id': `${SITE_URL}/#organization` },
  audience: {
    '@type': 'Audience',
    audienceType: 'Advogados e escritorios de advocacia brasileiros',
    geographicArea: { '@type': 'Country', name: 'Brasil' },
  },
  offers: {
    '@type': 'AggregateOffer',
    priceCurrency: 'BRL',
    lowPrice: '1399',
    highPrice: '1599',
    offerCount: 3,
    availability: 'https://schema.org/InStock',
    offers: [
      { '@type': 'Offer', name: 'Escritorio', price: '1399', priceCurrency: 'BRL', category: 'subscription', description: '1-5 advogados · 5 agentes essenciais', availability: 'https://schema.org/InStock' },
      { '@type': 'Offer', name: 'Firma',      price: '1459', priceCurrency: 'BRL', category: 'subscription', description: '6-15 advogados · 27 agentes',         availability: 'https://schema.org/InStock' },
      { '@type': 'Offer', name: 'Enterprise', price: '1599', priceCurrency: 'BRL', category: 'subscription', description: '16+ advogados · agentes customizados', availability: 'https://schema.org/InStock' },
    ],
  },
  featureList: [
    'Analise de documentos juridicos',
    'Pesquisa de jurisprudencia STF/STJ',
    'Redacao de pecas processuais',
    'Calculo de prazos e correcao monetaria',
    'Resumo automatico de contratos',
    'Traducao juridica PT/EN/ES',
    'Simulado OAB adaptativo',
    'Compliance LGPD + Provimento 205 OAB',
  ],
  softwareRequirements: 'Navegador moderno · conexao de internet',
  permissions: 'Nao requer instalacao local',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: `
          (function() {
            try {
              var t = localStorage.getItem('pralvex-theme');
              if (!t) t = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
              document.documentElement.setAttribute('data-theme', t);
            } catch(e) {
              document.documentElement.setAttribute('data-theme', 'dark');
            }
          })();
        `}} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
      </head>
      <body className={`${dmSans.variable} ${playfair.variable}`}>
        <a href="#main-content" className="skip-link">Pular para o conteudo</a>
        <ThemeProvider>{children}</ThemeProvider>
        <CookieConsent />
        <MicrosoftClarity />
      </body>
    </html>
  )
}
